name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -p:PackageVersion=0.9.${{github.run_number}}
    - name: Publish
      run: dotnet nuget push ./ReleaseDownloader/nupkg/ReleaseDownloader.*.nupkg -k ${{secrets.Nuget_API_Key}} -s nuget.org
